image: node:latest
stages:
  - build
  - test
  - deploy

before_script:
  - npm install
  - npm --prefix ./functions install

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build