image: node:8.12.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@8.3.19
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - dist/
  only:
    - master