image: node:latest
stages:
  - build
  - test
  - deploy

before_script:
  - npm install
  - npm --prefix ./functions install

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - npm run build
  only:
    - master
